<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\ServiceLetterTemplate;
use App\Models\User;
use Illuminate\Database\Seeder;
use RuntimeException;

/**
 * Comprehensive trilingual starter library for routine HR/service letters.
 *
 * IMPORTANT:
 * - These are editable administrative drafts, not substitutes for a specific
 *   Ministry/Public Administration circular, embassy form, regulator form or
 *   destination-country wording.
 * - Officers must review the generated draft and replace any [EDIT: ...]
 *   prompts before submission/approval.
 * - The seeder is idempotent: rerunning it updates the system starter
 *   templates without creating duplicates and does not delete custom templates.
 */
class ServiceLetterTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $creator = User::havingRole('super_admin')->orderBy('id')->first()
            ?? User::orderBy('id')->first();

        if (! $creator) {
            throw new RuntimeException('Create the Super Admin user before running ServiceLetterTemplateSeeder.');
        }

        foreach ($this->occasions() as $occasion) {
            foreach (['en', 'si', 'ta'] as $language) {
                ServiceLetterTemplate::updateOrCreate(
                    [
                        'name' => $occasion['name'],
                        'language' => $language,
                    ],
                    [
                        'description' => $occasion['description'][$language],
                        'body' => $this->body($language, $occasion['clause'][$language]),
                        'created_by' => $creator->id,
                        'is_active' => true,
                        'disabled_by' => null,
                        'disabled_at' => null,
                        'disable_reason' => null,
                    ],
                );
            }
        }

        $this->command?->info('Seeded/updated '.(count($this->occasions()) * 3).' trilingual service-letter templates.');
    }

    private function body(string $language, string $clause): string
    {
        return match ($language) {
            'si' => "අදාළ සියලු පාර්ශ්ව වෙත,\n\nසේවා සහතික කිරීම\n\nමෙයින් සහතික කරනු ලබන්නේ {{employee_name}} (ජාතික හැඳුනුම්පත් අංකය: {{nic_number}}, වැටුප් අංකය: {{pay_no}}) {{hospital_name}} හි {{position_title}} තනතුරේ සේවය කරන/සේවය කළ නිලධාරියෙකු/නිලධාරිනියක බවයි. වාර්තා අනුව පත්වීම් දිනය {{date_of_appointment}} වන අතර මෙම ආයතනයේ රාජකාරියට වාර්තා කළ දිනය {{date_reported_for_duty}} වේ. වර්තමාන සේවා ඒකකය {{unit_name}}, ශ්‍රේණිය {{current_grade}} සහ වැටුප් පරිමාණය {{salary_scale}} ලෙස සටහන් වී ඇත.\n\n{$clause}\n\nමෙම ලිපිය {{today}} දින නිල සේවා වාර්තා මත පදනම්ව නිකුත් කර ඇත. අවශ්‍ය නම් [සංස්කරණය කරන්න: ලබන්නා/ආයතනය/යොමු අංකය/විශේෂ අරමුණ] ඇතුළත් කර අවසන් ලිපිය අනුමැතියට පෙර සමාලෝචනය කළ යුතුය.",
            'ta' => "சம்பந்தப்பட்ட அனைவருக்கும்,\n\nசேவை உறுதிப்படுத்தல்\n\n{{employee_name}} (தேசிய அடையாள அட்டை இலக்கம்: {{nic_number}}, சம்பள இலக்கம்: {{pay_no}}) அவர்கள் {{hospital_name}} இல் {{position_title}} பதவியில் பணிபுரியும்/பணிபுரிந்த உத்தியோகத்தர் என்பதை இதன் மூலம் உறுதிப்படுத்துகிறோம். சேவைப் பதிவுகளின்படி நியமனத் திகதி {{date_of_appointment}} ஆகும்; இந்நிறுவனத்தில் கடமை ஏற்ற திகதி {{date_reported_for_duty}} ஆகும். தற்போதைய பணியிடம் {{unit_name}}, தரம் {{current_grade}}, சம்பள அளவுத்திட்டம் {{salary_scale}} எனப் பதிவாகியுள்ளது.\n\n{$clause}\n\nஇக்கடிதம் {{today}} அன்று அதிகாரப்பூர்வ சேவைப் பதிவுகளின் அடிப்படையில் வழங்கப்படுகிறது. தேவையான இடங்களில் [திருத்துக: பெறுநர்/நிறுவனம்/குறிப்பு இலக்கம்/சிறப்பு நோக்கம்] என்பவற்றை நிரப்பி, இறுதி கடிதம் அங்கீகாரத்திற்கு முன் பரிசீலிக்கப்பட வேண்டும்.",
            default => "TO WHOM IT MAY CONCERN\n\nSERVICE / EMPLOYMENT CERTIFICATION\n\nThis is to certify that {{employee_name}} (NIC: {{nic_number}}, Pay No.: {{pay_no}}) is/was an employee of {{hospital_name}} serving in the post of {{position_title}}. According to the official service record, the date of appointment is {{date_of_appointment}} and the date reported for duty at this institution is {{date_reported_for_duty}}. The recorded current unit is {{unit_name}}, grade is {{current_grade}}, and salary scale is {{salary_scale}}.\n\n{$clause}\n\nThis letter is issued on {{today}} on the basis of the official service record. Replace any [EDIT: recipient / institution / reference / specific purpose] text as applicable and review the final wording before approval.",
        };
    }

    private function occasions(): array
    {
        return [
            $this->o('01. General Service Confirmation', 'General factual service confirmation for routine official use.', 'සාමාන්‍ය නිල කටයුතු සඳහා මූලික සේවා තොරතුරු තහවුරු කිරීම.', 'பொதுவான அதிகாரப்பூர்வ பயன்பாட்டிற்கான அடிப்படை சேவை உறுதிப்படுத்தல்.',
                'This letter confirms the employee’s recorded service particulars for general official purposes.', 'මෙම ලිපිය සාමාන්‍ය නිල අවශ්‍යතා සඳහා නිලධාරියාගේ වාර්තාගත සේවා තොරතුරු තහවුරු කරයි.', 'இக்கடிதம் பொதுவான அதிகாரப்பூர்வ தேவைகளுக்காக உத்தியோகத்தரின் பதிவுசெய்யப்பட்ட சேவை விவரங்களை உறுதிப்படுத்துகிறது.'),
            $this->o('02. Detailed Service & Experience Certificate', 'Detailed service/experience certification for applications and credential review.', 'අයදුම්පත් සහ සුදුසුකම් පරීක්ෂාව සඳහා සවිස්තර සේවා/පළපුරුද්ද සහතිකය.', 'விண்ணப்பங்கள் மற்றும் தகுதி சரிபார்ப்பிற்கான விரிவான சேவை/அனுபவச் சான்றிதழ்.',
                'The employee’s experience is certified with reference to the above designation and service period. [EDIT: add verified duties/responsibilities and exact from/to dates where required].', 'ඉහත තනතුර හා සේවා කාලයට අදාළ පළපුරුද්ද මෙයින් සහතික කරයි. [සංස්කරණය කරන්න: අවශ්‍ය නම් තහවුරු කළ රාජකාරි/වගකීම් සහ නිශ්චිත ආරම්භ/අවසන් දින එක් කරන්න].', 'மேற்கண்ட பதவி மற்றும் சேவைக்காலத்துடன் தொடர்புடைய அனுபவம் இதன் மூலம் சான்றளிக்கப்படுகிறது. [திருத்துக: தேவையானால் சரிபார்க்கப்பட்ட கடமைகள்/பொறுப்புகள் மற்றும் துல்லியமான தொடக்கம்/முடிவு திகதிகளைச் சேர்க்கவும்].'),
            $this->o('03. Current Employment Verification', 'Confirms that the employee is presently employed at the institution.', 'නිලධාරියා දැනට ආයතනයේ සේවයේ නිරත බව තහවුරු කිරීම.', 'உத்தியோகத்தர் தற்போது நிறுவனத்தில் பணிபுரிவதை உறுதிப்படுத்தல்.',
                'As at {{today}}, the employee is recorded as being in active service at this institution, subject to the current service record.', '{{today}} දිනට නිල සේවා වාර්තාව අනුව නිලධාරියා මෙම ආයතනයේ සක්‍රීය සේවයේ නිරත බව සටහන් වේ.', '{{today}} நிலவரப்படி, அதிகாரப்பூர்வ சேவைப் பதிவின்படி உத்தியோகத்தர் இந்நிறுவனத்தில் செயலில் உள்ள சேவையில் இருப்பதாகப் பதிவாகியுள்ளது.'),
            $this->o('04. Appointment Confirmation', 'Confirms the recorded appointment and reporting-for-duty details.', 'පත්වීම සහ රාජකාරියට වාර්තා කිරීමේ වාර්තාගත තොරතුරු තහවුරු කිරීම.', 'நியமனம் மற்றும் கடமை ஏற்ற பதிவுசெய்யப்பட்ட விவரங்களை உறுதிப்படுத்தல்.',
                'The appointment and reporting-for-duty particulars stated above are confirmed from the official service record. [EDIT: add appointment type/permanent/probationary status only if verified].', 'ඉහත සඳහන් පත්වීම් සහ රාජකාරියට වාර්තා කළ තොරතුරු නිල සේවා වාර්තාවෙන් තහවුරු කර ඇත. [සංස්කරණය කරන්න: තහවුරු කර ඇත්නම් පමණක් පත්වීම් වර්ගය/ස්ථිර/පරිවාස තත්ත්වය එක් කරන්න].', 'மேற்கண்ட நியமன மற்றும் கடமை ஏற்ற விவரங்கள் அதிகாரப்பூர்வ சேவைப் பதிவிலிருந்து உறுதிப்படுத்தப்பட்டுள்ளன. [திருத்துக: சரிபார்க்கப்பட்டிருந்தால் மட்டுமே நியமன வகை/நிரந்தர/தகுதிகாண் நிலையைச் சேர்க்கவும்].'),
            $this->o('05. Designation & Duties Confirmation', 'Designation and verified duties/responsibilities confirmation.', 'තනතුර සහ තහවුරු කළ රාජකාරි/වගකීම් තහවුරු කිරීම.', 'பதவி மற்றும் சரிபார்க்கப்பட்ட கடமைகள்/பொறுப்புகள் உறுதிப்படுத்தல்.',
                'The designation is confirmed as stated above. [EDIT: insert only duties and responsibilities verified from the employee profile/service record].', 'ඉහත සඳහන් තනතුර තහවුරු කරයි. [සංස්කරණය කරන්න: සේවක පැතිකඩ/සේවා වාර්තාවෙන් තහවුරු කළ රාජකාරි සහ වගකීම් පමණක් එක් කරන්න].', 'மேற்கண்ட பதவி உறுதிப்படுத்தப்படுகிறது. [திருத்துக: பணியாளர் சுயவிவரம்/சேவைப் பதிவிலிருந்து சரிபார்க்கப்பட்ட கடமைகள் மற்றும் பொறுப்புகளை மட்டும் சேர்க்கவும்].'),
            $this->o('06. Salary & Employment Confirmation', 'Employment and recorded salary-scale confirmation for official financial purposes.', 'නිල මූල්‍ය අවශ්‍යතා සඳහා සේවය සහ වාර්තාගත වැටුප් පරිමාණය තහවුරු කිරීම.', 'அதிகாரப்பூர்வ நிதி தேவைகளுக்கான வேலைவாய்ப்பு மற்றும் பதிவுசெய்யப்பட்ட சம்பள அளவுத்திட்ட உறுதிப்படுத்தல்.',
                'The recorded salary scale is {{salary_scale}}. [EDIT: insert basic salary/gross salary only after verifying the current payroll record and the recipient’s requirement].', 'වාර්තාගත වැටුප් පරිමාණය {{salary_scale}} වේ. [සංස්කරණය කරන්න: වත්මන් වැටුප් ලේඛනයෙන් තහවුරු කළ පසු පමණක් මූලික/දළ වැටුප එක් කරන්න].', 'பதிவுசெய்யப்பட்ட சம்பள அளவுத்திட்டம் {{salary_scale}} ஆகும். [திருத்துக: தற்போதைய சம்பளப் பதிவை சரிபார்த்த பின்னரே அடிப்படை/மொத்த சம்பளத்தைச் சேர்க்கவும்].'),
            $this->o('07. Work & Conduct / Good Standing', 'Factual work-and-conduct/good-standing statement where service records support it.', 'සේවා වාර්තා මත පදනම් වූ වැඩ සහ හැසිරීම/යහපත් තත්ත්වය පිළිබඳ ප්‍රකාශය.', 'சேவைப் பதிவுகளால் ஆதரிக்கப்படும் பணிச் செயல்பாடு மற்றும் நன்னிலை அறிக்கை.',
                '[EDIT: after checking the disciplinary/service record, state whether work and conduct are satisfactory and whether the officer is in good standing. Do not make an unverified statement].', '[සංස්කරණය කරන්න: විනය/සේවා වාර්තාව පරීක්ෂා කර වැඩ හා හැසිරීම සතුටුදායකද සහ යහපත් තත්ත්වයේද යන්න සටහන් කරන්න. තහවුරු නොකළ ප්‍රකාශයක් නොකරන්න].', '[திருத்துக: ஒழுக்காற்று/சேவைப் பதிவை சரிபார்த்து பணியும் நடத்தையும் திருப்திகரமா, நன்னிலையில் உள்ளாரா என்பதை குறிப்பிடவும். சரிபார்க்கப்படாத அறிக்கையை இட வேண்டாம்].'),
            $this->o('08. No Disciplinary Action Confirmation', 'For applications requiring a factual disciplinary-status certification.', 'විනය තත්ත්වය පිළිබඳ කරුණුමය සහතිකයක් අවශ්‍ය අයදුම්පත් සඳහා.', 'ஒழுக்காற்று நிலை குறித்த உண்மைத்தகவல் சான்றிதழ் தேவைப்படும் விண்ணப்பங்களுக்கு.',
                '[EDIT: after checking the complete disciplinary record, state the applicable factual position regarding disciplinary action/inquiries. Delete this paragraph if the required check has not been completed].', '[සංස්කරණය කරන්න: සම්පූර්ණ විනය වාර්තාව පරීක්ෂා කර අදාළ විනය ක්‍රියාමාර්ග/විමර්ශන පිළිබඳ සත්‍ය තත්ත්වය සඳහන් කරන්න. පරීක්ෂාව සම්පූර්ණ නොකළේ නම් මෙම ඡේදය ඉවත් කරන්න].', '[திருத்துக: முழுமையான ஒழுக்காற்றுப் பதிவைச் சரிபார்த்து ஒழுக்காற்று நடவடிக்கை/விசாரணை தொடர்பான உண்மை நிலையை குறிப்பிடவும். சரிபார்ப்பு முடிக்கப்படாவிட்டால் இந்தப் பத்தியை நீக்கவும்].'),
            $this->o('09. Length of Service Confirmation', 'Confirms recorded service commencement and length for administrative use.', 'පරිපාලන අවශ්‍යතා සඳහා සේවා ආරම්භය සහ සේවා කාලය තහවුරු කිරීම.', 'நிர்வாக பயன்பாட்டிற்கான சேவை தொடக்கம் மற்றும் சேவைக்கால உறுதிப்படுத்தல்.',
                'The recorded commencement dates are shown above. [EDIT: calculate and insert completed years/months of service as at the required cut-off date, after checking any no-pay/interruptions if relevant].', 'වාර්තාගත ආරම්භක දින ඉහත දැක්වේ. [සංස්කරණය කරන්න: අදාළ නම් වැටුප් රහිත නිවාඩු/සේවා බිඳවැටීම් පරීක්ෂා කර අවශ්‍ය කඩඉම් දිනයට සම්පූර්ණ වසර/මාස ගණන ඇතුළත් කරන්න].', 'பதிவுசெய்யப்பட்ட தொடக்கத் திகதிகள் மேலே தரப்பட்டுள்ளன. [திருத்துக: தேவையானால் சம்பளமற்ற விடுப்பு/சேவை இடைநிறுத்தங்களைச் சரிபார்த்து குறிப்பிட்ட திகதிவரை நிறைவு செய்த ஆண்டுகள்/மாதங்களைச் சேர்க்கவும்].'),
            $this->o('10. Promotion / Grade Confirmation', 'Confirms current recorded grade and verified promotion details.', 'වත්මන් ශ්‍රේණිය සහ තහවුරු කළ උසස්වීම් තොරතුරු තහවුරු කිරීම.', 'தற்போதைய பதிவுசெய்யப்பட்ட தரம் மற்றும் சரிபார்க்கப்பட்ட பதவி உயர்வு விவரங்கள்.',
                'The current recorded grade is {{current_grade}}. [EDIT: add verified promotion date, effective date and promotion reference where required].', 'වත්මන් වාර්තාගත ශ්‍රේණිය {{current_grade}} වේ. [සංස්කරණය කරන්න: අවශ්‍ය නම් තහවුරු කළ උසස්වීම් දිනය, බලපැවැත්වෙන දිනය සහ යොමු අංකය එක් කරන්න].', 'தற்போதைய பதிவுசெய்யப்பட்ட தரம் {{current_grade}} ஆகும். [திருத்துக: தேவையானால் சரிபார்க்கப்பட்ட பதவி உயர்வு திகதி, அமல்படுத்தும் திகதி மற்றும் குறிப்பு இலக்கத்தைச் சேர்க்கவும்].'),
            $this->o('11. Increment / Salary Progression Confirmation', 'Confirms verified increment or salary-progression information.', 'තහවුරු කළ වැටුප් වර්ධක/වැටුප් ප්‍රගති තොරතුරු සඳහා.', 'சரிபார்க்கப்பட்ட சம்பள உயர்வு/சம்பள முன்னேற்ற விவரங்களுக்கு.',
                '[EDIT: insert the verified increment date, salary step and relevant payroll/service-record reference].', '[සංස්කරණය කරන්න: තහවුරු කළ වැටුප් වර්ධක දිනය, වැටුප් පියවර සහ අදාළ වැටුප්/සේවා වාර්තා යොමුව එක් කරන්න].', '[திருத்துக: சரிபார்க்கப்பட்ட சம்பள உயர்வு திகதி, சம்பள படிநிலை மற்றும் தொடர்புடைய சம்பள/சேவைப் பதிவு குறிப்பைச் சேர்க்கவும்].'),
            $this->o('12. Transfer Confirmation', 'Confirms an approved transfer in/out or internal transfer.', 'අනුමත මාරුවීමක්/අභ්‍යන්තර මාරුවීමක් තහවුරු කිරීම.', 'அங்கீகரிக்கப்பட்ட இடமாற்றம்/உள் இடமாற்றத்தை உறுதிப்படுத்தல்.',
                '[EDIT: state transfer direction, from/to institution or unit, effective date, and approved transfer reference].', '[සංස්කරණය කරන්න: මාරුවීමේ දිශාව, සිට/දක්වා ආයතනය හෝ ඒකකය, බලපැවැත්වෙන දිනය සහ අනුමත මාරු යොමුව සඳහන් කරන්න].', '[திருத்துக: இடமாற்ற திசை, இருந்து/செல்லும் நிறுவனம் அல்லது அலகு, அமல்படுத்தும் திகதி மற்றும் அங்கீகரிக்கப்பட்ட இடமாற்ற குறிப்பை குறிப்பிடவும்].'),
            $this->o('13. Release / Relieving Confirmation', 'Confirms official release/relieving following an approved decision.', 'අනුමත තීරණයකින් පසු නිල නිදහස් කිරීම/රාජකාරියෙන් මුදා හැරීම තහවුරු කිරීම.', 'அங்கீகரிக்கப்பட்ட தீர்மானத்திற்குப் பிந்தைய அதிகாரப்பூர்வ விடுவிப்பு உறுதிப்படுத்தல்.',
                '[EDIT: insert approved release/relieving date, destination and authority/reference. Do not imply clearance unless formally completed].', '[සංස්කරණය කරන්න: අනුමත නිදහස්/මුදාහැරීමේ දිනය, ගමනාන්තය සහ බලධාරී/යොමු අංකය එක් කරන්න. නිල නිමාවක් නොමැති නම් clearance සම්පූර්ණ බව නොපවසන්න].', '[திருத்துக: அங்கீகரிக்கப்பட்ட விடுவிப்பு திகதி, செல்லும் இடம் மற்றும் அதிகாரம்/குறிப்பு இலக்கத்தைச் சேர்க்கவும். முறையாக முடிக்கப்படாவிட்டால் clearance முடிந்தது எனக் குறிப்பிட வேண்டாம்].'),
            $this->o('14. Secondment / Temporary Release', 'For secondment, temporary attachment or temporary release certification.', 'ද්විතීයික පත්කිරීම/තාවකාලික අනුයුක්තිය/තාවකාලික නිදහස් කිරීම සඳහා.', 'இரண்டாம் நிலை நியமனம்/தற்காலிக இணைப்பு/தற்காலிக விடுவிப்பிற்காக.',
                '[EDIT: state secondment/temporary-release institution, period, effective dates and approving authority/reference].', '[සංස්කරණය කරන්න: ද්විතීයික පත්කිරීම/තාවකාලික නිදහස් ආයතනය, කාලය, බලපැවැත්වෙන දින සහ අනුමත බලධාරී/යොමුව සඳහන් කරන්න].', '[திருத்துக: secondment/தற்காலிக விடுவிப்பு நிறுவனம், காலம், அமல்படுத்தும் திகதிகள் மற்றும் அங்கீகரித்த அதிகாரம்/குறிப்பை குறிப்பிடவும்].'),
            $this->o('15. Retirement / Pension Service Confirmation', 'Service confirmation for retirement/pension administrative processing.', 'විශ්‍රාම/විශ්‍රාම වැටුප් පරිපාලන කටයුතු සඳහා සේවා තහවුරු කිරීම.', 'ஓய்வு/ஓய்வூதிய நிர்வாக நடவடிக்கைகளுக்கான சேவை உறுதிப்படுத்தல்.',
                '[EDIT: insert verified retirement date/type and pension/service particulars required by the receiving authority].', '[සංස්කරණය කරන්න: තහවුරු කළ විශ්‍රාම දිනය/වර්ගය සහ ලබන්නාට අවශ්‍ය විශ්‍රාම වැටුප්/සේවා තොරතුරු එක් කරන්න].', '[திருத்துக: சரிபார்க்கப்பட்ட ஓய்வு திகதி/வகை மற்றும் பெறுநர் அதிகாரிக்கு தேவையான ஓய்வூதிய/சேவை விவரங்களைச் சேர்க்கவும்].'),
            $this->o('16. Resignation / Separation Service Certificate', 'Factual service certificate after resignation or other separation.', 'ඉල්ලා අස්වීම හෝ වෙනත් සේවා අවසන්වීමෙන් පසු කරුණුමය සේවා සහතිකය.', 'ராஜினாமா அல்லது பிற சேவை முடிவுக்குப் பிந்தைய உண்மைத்தகவல் சேவைச் சான்றிதழ்.',
                '[EDIT: state verified final date of service and mode of separation; avoid statements on clearance unless verified].', '[සංස්කරණය කරන්න: තහවුරු කළ අවසන් සේවා දිනය සහ සේවා අවසන් වූ ආකාරය සඳහන් කරන්න; තහවුරු නොකළ clearance ප්‍රකාශ නොකරන්න].', '[திருத்துக: சரிபார்க்கப்பட்ட இறுதி சேவை திகதி மற்றும் சேவை முடிவு முறையை குறிப்பிடவும்; சரிபார்க்காத clearance அறிக்கைகளை இட வேண்டாம்].'),
            $this->o('17. Local Employment Application Support', 'Service verification for an application to another Sri Lankan employer/institution.', 'ශ්‍රී ලංකාවේ වෙනත් සේවාදායකයෙකු/ආයතනයකට අයදුම් කිරීම සඳහා සේවා තහවුරු කිරීම.', 'இலங்கையின் மற்றொரு தொழில்தருநர்/நிறுவனத்திற்கு விண்ணப்பிக்க சேவை உறுதிப்படுத்தல்.',
                'This certification is issued in support of an application within Sri Lanka. [EDIT: recipient, vacancy/post and application reference].', 'මෙම සහතිකය ශ්‍රී ලංකාව තුළ අයදුම්පතක් සඳහා නිකුත් කරයි. [සංස්කරණය කරන්න: ලබන්නා, පුරප්පාඩුව/තනතුර සහ අයදුම් යොමුව].', 'இச்சான்றிதழ் இலங்கைக்குள் உள்ள ஒரு விண்ணப்பத்திற்காக வழங்கப்படுகிறது. [திருத்துக: பெறுநர், காலியிடம்/பதவி மற்றும் விண்ணப்ப குறிப்பு].'),
            $this->o('18. Foreign Employment Application Support', 'Employment/service verification for overseas employment.', 'විදේශ රැකියා අයදුම්පතක් සඳහා සේවා/රැකියා තහවුරු කිරීම.', 'வெளிநாட்டு வேலைவாய்ப்பு விண்ணப்பத்திற்கான சேவை/வேலை உறுதிப்படுத்தல்.',
                'This certification is issued for an overseas employment application. [EDIT: destination country, employer/recruiter and post applied for].', 'මෙම සහතිකය විදේශ රැකියා අයදුම්පතක් සඳහා නිකුත් කරයි. [සංස්කරණය කරන්න: ගමනාන්ත රට, සේවාදායකයා/බඳවාගැනීමේ ආයතනය සහ අයදුම් කරන තනතුර].', 'இச்சான்றிதழ் வெளிநாட்டு வேலைவாய்ப்பு விண்ணப்பத்திற்காக வழங்கப்படுகிறது. [திருத்துக: செல்லும் நாடு, தொழில்தருநர்/ஆட்சேர்ப்பு நிறுவனம் மற்றும் விண்ணப்பிக்கும் பதவி].'),
            $this->o('19. Embassy / Visa Employment Verification', 'Factual employment verification addressed to an embassy, high commission or visa centre.', 'තානාපති කාර්යාල/මහ කොමසාරිස් කාර්යාල/වීසා මධ්‍යස්ථානය සඳහා රැකියා තහවුරු කිරීම.', 'தூதரகம்/உயர் ஆணையம்/விசா மையத்திற்கான வேலைவாய்ப்பு உறுதிப்படுத்தல்.',
                'This letter may be presented to [EDIT: embassy/high commission/visa centre] in connection with [EDIT: visa type/purpose]. It certifies employment facts only and does not guarantee a visa outcome.', 'මෙම ලිපිය [සංස්කරණය කරන්න: තානාපති/මහ කොමසාරිස්/වීසා මධ්‍යස්ථානය] වෙත [සංස්කරණය කරන්න: වීසා වර්ගය/අරමුණ] සඳහා ඉදිරිපත් කළ හැක. මෙය රැකියා කරුණු පමණක් තහවුරු කරයි; වීසා ප්‍රතිඵලයක් සහතික නොකරයි.', 'இக்கடிதம் [திருத்துக: தூதரகம்/உயர் ஆணையம்/விசா மையம்] இடம் [திருத்துக: விசா வகை/நோக்கம்] தொடர்பாக சமர்ப்பிக்கப்படலாம். இது வேலைவாய்ப்பு உண்மைகளை மட்டும் உறுதிப்படுத்துகிறது; விசா முடிவை உத்தரவாதப்படுத்தாது.'),
            $this->o('20. Work / Residence Permit Support', 'Employment facts for overseas work-permit or residence-permit processing.', 'විදේශ රැකියා/නේවාසික අවසරපත් ක්‍රියාවලිය සඳහා රැකියා කරුණු.', 'வெளிநாட்டு வேலை/வதிவிட அனுமதி செயல்முறைக்கான வேலைவாய்ப்பு உண்மைகள்.',
                'This letter is issued for [EDIT: country/authority] work/residence permit processing and certifies only the service facts held by this institution.', 'මෙම ලිපිය [සංස්කරණය කරන්න: රට/බලධාරියා] හි රැකියා/නේවාසික අවසරපත් ක්‍රියාවලිය සඳහා නිකුත් කර ඇති අතර මෙම ආයතනය සතුව ඇති සේවා කරුණු පමණක් තහවුරු කරයි.', 'இக்கடிதம் [திருத்துக: நாடு/அதிகாரம்] வேலை/வதிவிட அனுமதி செயல்முறைக்காக வழங்கப்படுகிறது; இந்நிறுவனத்திடம் உள்ள சேவை உண்மைகள் மட்டுமே உறுதிப்படுத்தப்படுகின்றன.'),
            $this->o('21. International Credential Verification (DataFlow / EPIC / WES etc.)', 'For third-party credential/employment verification organisations.', 'තෙවන පාර්ශ්ව සුදුසුකම්/රැකියා තහවුරු කිරීමේ ආයතන සඳහා.', 'மூன்றாம் தரப்பு தகுதி/வேலை சரிபார்ப்பு நிறுவனங்களுக்காக.',
                'This letter is prepared for [EDIT: verification body and case/reference number]. The receiving organisation should independently verify any additional fields it requires.', 'මෙම ලිපිය [සංස්කරණය කරන්න: තහවුරු කිරීමේ ආයතනය සහ case/reference අංකය] සඳහා සකස් කර ඇත. අවශ්‍ය අමතර ක්ෂේත්‍ර ලබන්නා විසින් ස්වාධීනව තහවුරු කළ යුතුය.', 'இக்கடிதம் [திருத்துக: சரிபார்ப்பு நிறுவனம் மற்றும் வழக்கு/குறிப்பு இலக்கம்] க்காக தயாரிக்கப்பட்டுள்ளது. தேவையான கூடுதல் புலங்களை பெறுநர் நிறுவனம் தனித்தனியாக சரிபார்க்க வேண்டும்.'),
            $this->o('22. Higher Education / University Application', 'Service confirmation for local or overseas higher-education applications.', 'දේශීය හෝ විදේශ උසස් අධ්‍යාපන අයදුම්පත් සඳහා සේවා තහවුරු කිරීම.', 'உள்நாட்டு அல்லது வெளிநாட்டு உயர் கல்வி விண்ணப்பங்களுக்கான சேவை உறுதிப்படுத்தல்.',
                'This letter is issued in support of an application to [EDIT: university/institute/programme]. [EDIT: include verified professional experience relevant to the programme if required].', 'මෙම ලිපිය [සංස්කරණය කරන්න: විශ්වවිද්‍යාලය/ආයතනය/පාඨමාලාව] වෙත අයදුම් කිරීම සඳහා නිකුත් කරයි. [සංස්කරණය කරන්න: අවශ්‍ය නම් පාඨමාලාවට අදාළ තහවුරු කළ වෘත්තීය පළපුරුද්ද එක් කරන්න].', 'இக்கடிதம் [திருத்துக: பல்கலைக்கழகம்/நிறுவனம்/பாடநெறி] விண்ணப்பத்திற்காக வழங்கப்படுகிறது. [திருத்துக: தேவையானால் பாடநெறியுடன் தொடர்புடைய சரிபார்க்கப்பட்ட தொழில்முறை அனுபவத்தைச் சேர்க்கவும்].'),
            $this->o('23. Scholarship / Fellowship Application', 'Service confirmation supporting a scholarship or fellowship application.', 'ශිෂ්‍යත්ව/ෆෙලෝෂිප් අයදුම්පතක් සඳහා සේවා තහවුරු කිරීම.', 'புலமைப்பரிசில்/பெல்லோஷிப் விண்ணப்பத்திற்கான சேவை உறுதிப்படுத்தல்.',
                'This certification supports the application for [EDIT: scholarship/fellowship/programme and host institution]. Any release, funding or leave approval is subject to separate formal approval.', 'මෙම සහතිකය [සංස්කරණය කරන්න: ශිෂ්‍යත්වය/ෆෙලෝෂිප්/පාඨමාලාව සහ සත්කාරක ආයතනය] සඳහා අයදුම්පතට සහාය වේ. නිදහස් කිරීම, අරමුදල් හෝ නිවාඩු සඳහා වෙනම නිල අනුමැතිය අවශ්‍ය වේ.', 'இச்சான்றிதழ் [திருத்துக: புலமைப்பரிசில்/பெல்லோஷிப்/பாடநெறி மற்றும் வரவேற்பு நிறுவனம்] விண்ணப்பத்துக்கு ஆதரவாக வழங்கப்படுகிறது. விடுவிப்பு, நிதி அல்லது விடுப்பு தனியான முறையான அங்கீகாரத்திற்கு உட்பட்டது.'),
            $this->o('24. Local Training / Course Nomination Support', 'Employment/service confirmation for local training nomination or application.', 'දේශීය පුහුණුවකට නම් කිරීම/අයදුම් කිරීම සඳහා සේවා තහවුරු කිරීම.', 'உள்நாட்டு பயிற்சி நியமனம்/விண்ணப்பத்திற்கான சேவை உறுதிப்படுத்தல்.',
                'This letter supports participation/application for [EDIT: local course/training, organiser and dates]. Attendance remains subject to the applicable approval and duty-cover arrangements.', 'මෙම ලිපිය [සංස්කරණය කරන්න: දේශීය පාඨමාලාව/පුහුණුව, සංවිධායකයා සහ දින] සඳහා සහභාගී වීම/අයදුම් කිරීම සඳහා සහාය වේ. සහභාගීත්වය අදාළ අනුමැතිය සහ රාජකාරි ආවරණයට යටත් වේ.', 'இக்கடிதம் [திருத்துக: உள்நாட்டு பாடநெறி/பயிற்சி, ஏற்பாட்டாளர் மற்றும் திகதிகள்] பங்கேற்பு/விண்ணப்பத்திற்கு ஆதரவாகும். பங்கேற்பு தேவையான அங்கீகாரம் மற்றும் கடமை ஏற்பாடுகளுக்கு உட்பட்டது.'),
            $this->o('25. Foreign Training / Fellowship NOC', 'Draft NOC/service confirmation for approved or proposed overseas training/fellowship.', 'විදේශ පුහුණුව/ෆෙලෝෂිප් සඳහා NOC/සේවා තහවුරු කිරීමේ කෙටුම්පත.', 'வெளிநாட்டு பயிற்சி/பெல்லோஷிப் NOC/சேவை உறுதிப்படுத்தல் வரைவு.',
                '[EDIT: identify programme, country, host, dates, funding and the exact approving authority]. This template does not itself constitute approval for foreign leave, release, allowances or funding.', '[සංස්කරණය කරන්න: පාඨමාලාව, රට, සත්කාරක ආයතනය, දින, අරමුදල් සහ නිශ්චිත අනුමත බලධාරියා සඳහන් කරන්න]. මෙම කෙටුම්පත පමණින් විදේශ නිවාඩු/නිදහස් කිරීම/දීමනා/අරමුදල් අනුමත නොවේ.', '[திருத்துக: பாடநெறி, நாடு, வரவேற்பு நிறுவனம், திகதிகள், நிதி மற்றும் சரியான அங்கீகார அதிகாரத்தை குறிப்பிடவும்]. இந்த வரைவு மட்டும் வெளிநாட்டு விடுப்பு/விடுவிப்பு/கொடுப்பனவு/நிதி அங்கீகாரம் அல்ல.'),
            $this->o('26. Overseas Conference / Workshop NOC', 'Draft factual NOC/support letter for an overseas conference, workshop or meeting.', 'විදේශ සම්මන්ත්‍රණ/වැඩමුළු/රැස්වීමක් සඳහා NOC/සහාය ලිපි කෙටුම්පත.', 'வெளிநாட்டு மாநாடு/பட்டறை/கூட்டத்திற்கான NOC/ஆதரவு கடித வரைவு.',
                '[EDIT: event, organiser, country, dates, leave category, funding and approving authority]. Issue only after checking the applicable foreign-travel/training approvals.', '[සංස්කරණය කරන්න: උත්සවය, සංවිධායකයා, රට, දින, නිවාඩු වර්ගය, අරමුදල් සහ අනුමත බලධාරියා]. අදාළ විදේශ ගමන්/පුහුණු අනුමැති පරීක්ෂා කළ පසු පමණක් නිකුත් කරන්න.', '[திருத்துக: நிகழ்வு, ஏற்பாட்டாளர், நாடு, திகதிகள், விடுப்பு வகை, நிதி மற்றும் அங்கீகார அதிகாரம்]. பொருந்தும் வெளிநாட்டு பயணம்/பயிற்சி அங்கீகாரங்களை சரிபார்த்த பின்னரே வழங்கவும்.'),
            $this->o('27. Professional Registration / Licensing Support', 'Service/experience verification for a professional council or licensing authority.', 'වෘත්තීය සභාවක්/බලපත්‍ර අධිකාරියක් සඳහා සේවා/පළපුරුද්ද තහවුරු කිරීම.', 'தொழில்முறை சபை/உரிமம் வழங்கும் அதிகாரத்திற்கான சேவை/அனுபவ உறுதிப்படுத்தல்.',
                'This letter is issued for [EDIT: regulator/council, jurisdiction and application/reference]. [EDIT: add only verified scope of practice/duties/hours if specifically required].', 'මෙම ලිපිය [සංස්කරණය කරන්න: නියාමක/සභාව, අධිකරණ බල ප්‍රදේශය සහ අයදුම්/යොමුව] සඳහා නිකුත් කරයි. [සංස්කරණය කරන්න: විශේෂයෙන් අවශ්‍ය නම් තහවුරු කළ සේවා ක්ෂේත්‍රය/රාජකාරි/පැය පමණක් එක් කරන්න].', 'இக்கடிதம் [திருத்துக: ஒழுங்குபடுத்தி/சபை, அதிகாரப்பரப்பு மற்றும் விண்ணப்ப/குறிப்பு] க்காக வழங்கப்படுகிறது. [திருத்துக: குறிப்பாக தேவைப்பட்டால் சரிபார்க்கப்பட்ட பணிவாய்ப்பு/கடமைகள்/மணிநேரத்தை மட்டும் சேர்க்கவும்].'),
            $this->o('28. Bank / Loan / Financial Institution Confirmation', 'Employment and salary-scale confirmation for banks or other financial institutions.', 'බැංකු/මූල්‍ය ආයතන සඳහා රැකියා සහ වැටුප් පරිමාණ තහවුරු කිරීම.', 'வங்கி/நிதி நிறுவனங்களுக்கான வேலை மற்றும் சம்பள அளவுத்திட்ட உறுதிப்படுத்தல்.',
                'This certification is issued to [EDIT: bank/financial institution] for [EDIT: facility/loan purpose]. It is not a guarantee by the hospital of the employee’s financial obligation.', 'මෙම සහතිකය [සංස්කරණය කරන්න: බැංකුව/මූල්‍ය ආයතනය] වෙත [සංස්කරණය කරන්න: පහසුකම/ණය අරමුණ] සඳහා නිකුත් කරයි. මෙය සේවකයාගේ මූල්‍ය බැඳීම සඳහා රෝහලේ ඇපයක් නොවේ.', 'இச்சான்றிதழ் [திருத்துக: வங்கி/நிதி நிறுவனம்] க்கு [திருத்துக: வசதி/கடன் நோக்கம்] வழங்கப்படுகிறது. இது பணியாளரின் நிதி கடமைக்கு மருத்துவமனையின் உத்தரவாதம் அல்ல.'),
            $this->o('29. Housing / Rental / Address Confirmation', 'Employment/workplace confirmation for housing, rental or official-address purposes.', 'නිවාස/කුලී/නිල ලිපිනය සඳහා රැකියා/සේවාස්ථාන තහවුරු කිරීම.', 'வீடு/வாடகை/அதிகாரப்பூர்வ முகவரி நோக்கத்திற்கான வேலை/பணியிடம் உறுதிப்படுத்தல்.',
                'This letter confirms the employee’s workplace/service details for [EDIT: housing/rental/address purpose]. It does not certify a residential address unless separately verified.', 'මෙම ලිපිය [සංස්කරණය කරන්න: නිවාස/කුලී/ලිපිනය අරමුණ] සඳහා සේවාස්ථාන/සේවා තොරතුරු තහවුරු කරයි. වෙනම තහවුරු කර නොමැති නම් නේවාසික ලිපිනයක් තහවුරු නොකරයි.', 'இக்கடிதம் [திருத்துக: வீடு/வாடகை/முகவரி நோக்கம்] க்காக பணியிடம்/சேவை விவரங்களை உறுதிப்படுத்துகிறது. தனியாக சரிபார்க்கப்படாவிட்டால் வசிப்பிட முகவரியை உறுதிப்படுத்தாது.'),
            $this->o('30. Court / Legal / Statutory Authority Service Verification', 'Factual service verification requested by a court, tribunal or statutory/public authority.', 'අධිකරණ/විනිශ්චය මණ්ඩල/ව්‍යවස්ථාපිත හෝ රාජ්‍ය අධිකාරියකට සේවා තහවුරු කිරීම.', 'நீதிமன்றம்/தீர்ப்பாயம்/சட்டபூர்வ அல்லது பொது அதிகாரத்திற்கான சேவை உறுதிப்படுத்தல்.',
                'This response is provided to [EDIT: authority] under reference [EDIT: reference]. Only facts supported by the official service record should remain in the final letter.', 'මෙම පිළිතුර [සංස්කරණය කරන්න: අධිකාරිය] වෙත [සංස්කරණය කරන්න: යොමුව] යටතේ ලබා දෙයි. අවසන් ලිපියේ නිල සේවා වාර්තාවෙන් තහවුරු වන කරුණු පමණක් තබන්න.', 'இப்பதில் [திருத்துக: அதிகாரம்] க்கு [திருத்துக: குறிப்பு] கீழ் வழங்கப்படுகிறது. இறுதி கடிதத்தில் அதிகாரப்பூர்வ சேவைப் பதிவால் ஆதரிக்கப்படும் உண்மைகள் மட்டுமே இருக்க வேண்டும்.'),
            $this->o('31. Insurance / Benefit Claim Employment Confirmation', 'Employment/service confirmation for an insurance or benefit claim.', 'රක්ෂණ/ප්‍රතිලාභ හිමිකම් සඳහා රැකියා/සේවා තහවුරු කිරීම.', 'காப்பீடு/நலன் கோரிக்கைக்கான வேலை/சேவை உறுதிப்படுத்தல்.',
                'This letter is issued for [EDIT: insurer/benefit scheme and claim/reference]. Medical, accident or claim facts not held in the HR service record must not be inferred.', 'මෙම ලිපිය [සංස්කරණය කරන්න: රක්ෂණ සමාගම/ප්‍රතිලාභ යෝජනා ක්‍රමය සහ claim/reference] සඳහා නිකුත් කරයි. HR සේවා වාර්තාවේ නොමැති වෛද්‍ය/අනතුරු/හිමිකම් කරුණු අනුමාන නොකරන්න.', 'இக்கடிதம் [திருத்துக: காப்பீட்டாளர்/நலத்திட்டம் மற்றும் கோரிக்கை/குறிப்பு] க்காக வழங்கப்படுகிறது. HR சேவைப் பதிவில் இல்லாத மருத்துவ/விபத்து/கோரிக்கை உண்மைகளை ஊகிக்க வேண்டாம்.'),
            $this->o('32. Research / Academic Appointment Support', 'Service confirmation for research, academic, teaching or collaborative appointments.', 'පර්යේෂණ/අධ්‍යයන/ඉගැන්වීම්/සහයෝගී පත්වීම් සඳහා සේවා තහවුරු කිරීම.', 'ஆராய்ச்சி/கல்வி/கற்பித்தல்/ஒத்துழைப்பு நியமனங்களுக்கான சேவை உறுதிப்படுத்தல்.',
                'This letter supports [EDIT: research/academic appointment, institution and role]. Any institutional permission, ethics approval or release must be evidenced separately.', 'මෙම ලිපිය [සංස්කරණය කරන්න: පර්යේෂණ/අධ්‍යයන පත්වීම, ආයතනය සහ භූමිකාව] සඳහා සහාය වේ. ආයතනික අවසර/ආචාරධර්ම අනුමැතිය/නිදහස් කිරීම වෙනම සාක්ෂිගත කළ යුතුය.', 'இக்கடிதம் [திருத்துக: ஆராய்ச்சி/கல்வி நியமனம், நிறுவனம் மற்றும் பங்கு] க்கு ஆதரவாகும். நிறுவன அனுமதி/நெறிமுறை அங்கீகாரம்/விடுவிப்பு தனியாக ஆதாரப்படுத்தப்பட வேண்டும்.'),
            $this->o('33. Internship / Clinical Attachment Confirmation', 'Confirmation of a verified internship, clinical attachment or supervised placement.', 'තහවුරු කළ ඉන්ටර්න්ෂිප්/සායනික අනුයුක්තිය/අධීක්ෂිත ස්ථානගත කිරීම තහවුරු කිරීම.', 'சரிபார்க்கப்பட்ட இன்டர்ன்ஷிப்/மருத்துவ இணைப்பு/மேற்பார்வைப் பயிற்சி உறுதிப்படுத்தல்.',
                '[EDIT: insert verified attachment/internship title, department/unit, supervisor, exact period and status/completion where recorded].', '[සංස්කරණය කරන්න: තහවුරු කළ ඉන්ටර්න්ෂිප්/අනුයුක්ති නාමය, දෙපාර්තමේන්තුව/ඒකකය, අධීක්ෂකයා, නිශ්චිත කාලය සහ වාර්තාගත සම්පූර්ණ කිරීමේ තත්ත්වය එක් කරන්න].', '[திருத்துக: சரிபார்க்கப்பட்ட இன்டர்ன்ஷிப்/இணைப்பு பெயர், துறை/அலகு, மேற்பார்வையாளர், துல்லிய காலம் மற்றும் பதிவுசெய்யப்பட்ட நிறைவு நிலையைச் சேர்க்கவும்].'),
            $this->o('34. Teaching / Training Experience Confirmation', 'Verification of recorded teaching, supervision or staff-training experience.', 'වාර්තාගත ඉගැන්වීම්/අධීක්ෂණ/කාර්ය මණ්ඩල පුහුණු පළපුරුද්ද තහවුරු කිරීම.', 'பதிவுசெய்யப்பட்ட கற்பித்தல்/மேற்பார்வை/பணியாளர் பயிற்சி அனுபவ உறுதிப்படுத்தல்.',
                '[EDIT: insert only verified teaching/training roles, programmes, audience, period and hours where documented].', '[සංස්කරණය කරන්න: ලේඛනගත කර ඇති තහවුරු කළ ඉගැන්වීම්/පුහුණු භූමිකා, පාඨමාලා, පිරිස, කාලය සහ පැය පමණක් එක් කරන්න].', '[திருத்துக: ஆவணப்படுத்தப்பட்ட சரிபார்க்கப்பட்ட கற்பித்தல்/பயிற்சி பங்குகள், நிகழ்ச்சிகள், பயனாளர்கள், காலம் மற்றும் மணிநேரத்தை மட்டும் சேர்க்கவும்].'),
            $this->o('35. Official Foreign Mission / Duty Travel Confirmation', 'Service confirmation for an approved official overseas mission/duty journey.', 'අනුමත නිල විදේශ මෙහෙයුමක්/රාජකාරි ගමනක් සඳහා සේවා තහවුරු කිරීම.', 'அங்கீகரிக்கப்பட்ட அதிகாரப்பூர்வ வெளிநாட்டு பணிப்பயணத்திற்கான சேவை உறுதிப்படுத்தல்.',
                '[EDIT: insert mission/event, country, official-duty dates, funding, and approval/reference]. Do not use this template to bypass required foreign-travel approvals.', '[සංස්කරණය කරන්න: මෙහෙයුම/උත්සවය, රට, නිල රාජකාරි දින, අරමුදල් සහ අනුමැතිය/යොමුව එක් කරන්න]. අවශ්‍ය විදේශ ගමන් අනුමැති මඟහැරීමට මෙම කෙටුම්පත භාවිත නොකරන්න.', '[திருத்துக: பணி/நிகழ்வு, நாடு, அதிகாரப்பூர்வ பணித் திகதிகள், நிதி மற்றும் அங்கீகாரம்/குறிப்பு சேர்க்கவும்]. தேவையான வெளிநாட்டு பயண அங்கீகாரங்களை தவிர்க்க இவ்வார்ப்புருவைப் பயன்படுத்த வேண்டாம்.'),
            $this->o('36. General No-Objection Letter (NOC)', 'Generic NOC draft requiring purpose-specific review and competent-authority approval.', 'අරමුණට අදාළ සමාලෝචනය සහ බලයලත් අනුමැතිය අවශ්‍ය සාමාන්‍ය NOC කෙටුම්පත.', 'நோக்கத்திற்கேற்ற பரிசீலனை மற்றும் தகுதியான அதிகார அங்கீகாரம் தேவைப்படும் பொதுவான NOC வரைவு.',
                'Subject to the applicable rules and approvals, [EDIT: state the exact matter for which no objection is recorded]. This draft is not valid as an NOC until approved by the competent authority.', 'අදාළ නීති සහ අනුමැතිවලට යටත්ව [සංස්කරණය කරන්න: විරෝධතාවක් නොමැති බව සටහන් කරන නිශ්චිත කාරණය] සඳහන් කරන්න. බලයලත් අධිකාරිය අනුමත කරන තෙක් මෙම කෙටුම්පත වලංගු NOC එකක් නොවේ.', 'பொருந்தும் விதிகள் மற்றும் அங்கீகாரங்களுக்கு உட்பட்டு [திருத்துக: எதிர்ப்பு இல்லை எனப் பதிவு செய்யப்படும் துல்லியமான விடயம்] குறிப்பிடவும். தகுதியான அதிகாரம் அங்கீகரிக்கும் வரை இவ்வரைவு செல்லுபடியாகும் NOC அல்ல.'),
            $this->o('37. Passport / Immigration Factual Employment Letter', 'Factual employment letter for passport or immigration administration.', 'ගමන් බලපත්‍ර/ආගමන පරිපාලනය සඳහා කරුණුමය රැකියා ලිපිය.', 'கடவுச்சீட்டு/குடிவரவு நிர்வாகத்திற்கான உண்மைத்தகவல் வேலைவாய்ப்பு கடிதம்.',
                'This letter is issued for [EDIT: passport/immigration purpose and authority]. It confirms service facts only; immigration eligibility is determined by the relevant authority.', 'මෙම ලිපිය [සංස්කරණය කරන්න: ගමන් බලපත්‍ර/ආගමන අරමුණ සහ අධිකාරිය] සඳහා නිකුත් කරයි. මෙය සේවා කරුණු පමණක් තහවුරු කරයි; ආගමන සුදුසුකම අදාළ අධිකාරිය තීරණය කරයි.', 'இக்கடிதம் [திருத்துக: கடவுச்சீட்டு/குடிவரவு நோக்கம் மற்றும் அதிகாரம்] க்காக வழங்கப்படுகிறது. இது சேவை உண்மைகளை மட்டும் உறுதிப்படுத்துகிறது; குடிவரவு தகுதியை தொடர்புடைய அதிகாரம் தீர்மானிக்கும்.'),
            $this->o('38. Former Employee Service Certificate', 'Service certificate for a former employee based on historical records.', 'පෙර සේවකයෙකු සඳහා ඉතිහාස සේවා වාර්තා මත සේවා සහතිකය.', 'முன்னாள் பணியாளருக்கான வரலாற்றுச் சேவைப் பதிவுகளின் அடிப்படையிலான சேவைச் சான்றிதழ்.',
                '[EDIT: replace current-service wording as necessary and insert verified final service date, last post/unit and separation details].', '[සංස්කරණය කරන්න: අවශ්‍ය පරිදි වත්මන් සේවා වචන වෙනස් කර තහවුරු කළ අවසන් සේවා දිනය, අවසන් තනතුර/ඒකකය සහ සේවා අවසන් තොරතුරු එක් කරන්න].', '[திருத்துக: தேவையானபடி தற்போதைய சேவை சொற்களை மாற்றி சரிபார்க்கப்பட்ட இறுதி சேவை திகதி, கடைசி பதவி/அலகு மற்றும் சேவை முடிவு விவரங்களைச் சேர்க்கவும்].'),
            $this->o('39. Public Service / Competitive Examination Application Certification', 'Service confirmation supporting a public-service or competitive-examination application.', 'රාජ්‍ය සේවා/තරඟ විභාග අයදුම්පතක් සඳහා සේවා තහවුරු කිරීම.', 'அரச சேவை/போட்டித் தேர்வு விண்ணப்பத்திற்கான சேவை உறுதிப்படுத்தல்.',
                'This letter supports the application for [EDIT: examination/post/circular reference]. [EDIT: include verified eligibility facts requested by the circular, including work/conduct/disciplinary status only after checking the record].', 'මෙම ලිපිය [සංස්කරණය කරන්න: විභාගය/තනතුර/චක්‍රලේඛ යොමුව] සඳහා අයදුම්පතට සහාය වේ. [සංස්කරණය කරන්න: චක්‍රලේඛයෙන් ඉල්ලා ඇති සුදුසුකම් කරුණු, වැඩ/හැසිරීම/විනය තත්ත්වය වාර්තාව පරීක්ෂා කළ පසු පමණක් එක් කරන්න].', 'இக்கடிதம் [திருத்துக: தேர்வு/பதவி/சுற்றறிக்கை குறிப்பு] விண்ணப்பத்துக்கு ஆதரவாகும். [திருத்துக: சுற்றறிக்கையில் கோரப்படும் தகுதி உண்மைகள், பணி/நடத்தை/ஒழுக்காற்று நிலை ஆகியவற்றை பதிவைச் சரிபார்த்த பின்னரே சேர்க்கவும்].'),
            $this->o('40. Factual Employer Reference', 'Neutral factual employer reference without subjective recommendation.', 'විෂයමය නිර්දේශයකින් තොරව කරුණුමය සේවාදායක යොමු ලිපිය.', 'தனிப்பட்ட பரிந்துரையில்லாத நடுநிலை உண்மைத்தகவல் தொழில்தருநர் குறிப்பு.',
                'At the employee’s request, this reference confirms the factual employment details recorded by the institution. [EDIT: add verified duties/achievements only where documentary evidence exists; avoid unsupported opinions].', 'සේවකයාගේ ඉල්ලීම මත මෙම යොමු ලිපිය ආයතනයේ වාර්තාගත රැකියා කරුණු තහවුරු කරයි. [සංස්කරණය කරන්න: ලේඛනමය සාක්ෂි ඇති විට පමණක් තහවුරු කළ රාජකාරි/ජයග්‍රහණ එක් කරන්න; පදනම් රහිත අදහස් නොදක්වන්න].', 'பணியாளரின் கோரிக்கையின் பேரில், இக்குறிப்பு நிறுவனம் பதிவுசெய்துள்ள வேலைவாய்ப்பு உண்மைகளை உறுதிப்படுத்துகிறது. [திருத்துக: ஆவண ஆதாரம் உள்ளபோது மட்டுமே சரிபார்க்கப்பட்ட கடமைகள்/சாதனைகளைச் சேர்க்கவும்; ஆதாரமற்ற கருத்துகளை தவிர்க்கவும்].'),
        ];
    }

    private function o(string $name, string $enDesc, string $siDesc, string $taDesc, string $enClause, string $siClause, string $taClause): array
    {
        return [
            'name' => $name,
            'description' => ['en' => $enDesc, 'si' => $siDesc, 'ta' => $taDesc],
            'clause' => ['en' => $enClause, 'si' => $siClause, 'ta' => $taClause],
        ];
    }
}
