<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Employee Profile Handling Progress</title>
    <style>
        @page {
            margin: 24px 26px;
        }

        body {
            font-family: Arial, sans-serif;
            color: #20384d;
            font-size: 11pt;
            line-height: 1.42;
        }

        h1 {
            font-size: 20pt;
            margin: 0 0 5px;
            color: #174f7a;
        }

        .sub {
            color: #687e90;
            margin-bottom: 14px;
            font-size: 10.5pt;
        }

        .meta {
            width: 100%;
            margin-bottom: 12px;
            border-collapse: collapse;
        }

        .meta td {
            padding: 4px 5px;
            font-size: 9.5pt;
        }

        .summary {
            width: 100%;
            border-collapse: separate;
            border-spacing: 6px;
            margin: 0 -6px 12px;
        }

        .summary td {
            border: 1px solid #d8e2ea;
            border-radius: 5px;
            padding: 11px;
            background: #f7fafc;
        }

        .summary .label {
            color: #6e8293;
            font-size: 9.5pt;
        }

        .summary .value {
            font-size: 17pt;
            font-weight: bold;
            color: #173f60;
            margin-top: 4px;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
        }

        .data th {
            background: #eaf2f8;
            color: #35546d;
            font-size: 9.5pt;
            text-transform: uppercase;
            padding: 8px 6px;
            border: 1px solid #ccdbe6;
            line-height: 1.3;
        }

        .data td {
            padding: 8px 6px;
            border: 1px solid #d7e1e9;
            vertical-align: top;
            font-size: 10.5pt;
            line-height: 1.38;
        }

        .good {
            color: #167646;
            font-weight: bold;
        }

        .warn {
            color: #996000;
            font-weight: bold;
        }

        .muted {
            color: #74889a;
        }

        .footer {
            margin-top: 12px;
            padding-top: 8px;
            border-top: 1px solid #d7e1e9;
            color: #74889a;
            font-size: 9pt;
            line-height: 1.4;
        }
    </style>
</head>

<body>
    <h1>Employee Profile Handling Count Progress</h1>
    <div class="sub">Governed progress report based on each Subject Officer's official total Handling Count and
        current active mapped employee profiles.</div>

    <table class="meta">
        <tr>
            <td><strong>Generated:</strong> {{ $generatedAt->format('d M Y H:i') }}</td>
            <td><strong>Generated by:</strong> {{ $generatedBy }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Export scope:</strong>
                {{ $selectedOfficer ? 'Subject Officer: ' . $selectedOfficer['officer_name'] : 'All authorised Subject Officers' }}
            </td>
        </tr>
    </table>

    <table class="summary">
        <tr>
            <td>
                <div class="label">Total Handling Count</div>
                <div class="value">{{ number_format($summary['handling_count']) }}</div>
            </td>
            <td>
                <div class="label">Current Profile Count</div>
                <div class="value">{{ number_format($summary['profile_count']) }}</div>
            </td>
            <td>
                <div class="label">Remaining</div>
                <div class="value">{{ number_format($summary['remaining_count']) }}</div>
            </td>
            <td>
                <div class="label">Completion</div>
                <div class="value">
                    {{ $summary['completion_pct'] === null ? '—' : number_format($summary['completion_pct'], 1) . '%' }}
                </div>
            </td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th>#</th>
                <th>Subject Officer</th>
                <th>Subject Codes</th>
                <th>Handling</th>
                <th>Profiles</th>
                <th>Remaining</th>
                <th>Completion</th>
                <th>Status</th>
                <th>Current Profiles by Post</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $index => $row)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $row['officer_name'] }}</strong></td>
                    <td>{{ count($row['subject_codes']) ? implode(', ', $row['subject_codes']) : 'Effective HR scope' }}
                    </td>
                    <td>{{ $row['handling_count'] === null ? 'Not set' : number_format($row['handling_count']) }}</td>
                    <td>{{ number_format($row['profile_count']) }}</td>
                    <td>{{ $row['remaining_count'] === null ? '—' : number_format($row['remaining_count']) }}</td>
                    <td>{{ $row['completion_pct'] === null ? '—' : number_format($row['completion_pct'], 1) . '%' }}
                    </td>
                    <td
                        class="{{ $row['status'] === 'completed' ? 'good' : ($row['status'] === 'in_progress' ? 'warn' : '') }}">
                        {{ ucwords(str_replace('_', ' ', $row['status'])) }}</td>
                    <td>
                        @forelse ($row['position_breakdown'] as $position)
                            {{ $position['position_title'] }}: {{ number_format($position['profile_count']) }}
                            @if (!$loop->last)
                                ;
                            @endif
                        @empty
                            <span class="muted">No current profiles</span>
                        @endforelse
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">No Subject Officer records in the authorised scope.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        This report is a monitoring aid. Handling Count is officer-level; position figures are informational breakdowns
        only. Access and export scope follows the authenticated user's existing role permissions.
    </div>
</body>

</html>
