<?php

namespace App\Services;

use Illuminate\Http\UploadedFile;
use Illuminate\Validation\ValidationException;

/**
 * Central security gate for uploaded files.
 *
 * Laravel validation remains responsible for business-specific MIME/size rules.
 * This service adds cross-cutting controls required by the Sri Lanka CERT
 * guidance: suspicious-name checks and an optional anti-malware scan before
 * the file is persisted or processed.
 */
class SecureUploadService
{
    public static function assertSafe(UploadedFile $file, string $field = 'file'): void
    {
        if (! $file->isValid()) {
            self::reject($field, 'The uploaded file could not be validated.');
        }

        $original = (string) $file->getClientOriginalName();
        $basename = basename(str_replace(["\0", "\r", "\n"], '', $original));

        if ($basename === '' || $basename !== $original) {
            self::reject($field, 'The uploaded file name is not permitted.');
        }

        // Reject control characters and path traversal / path separator tricks.
        if (preg_match('/[\x00-\x1F\x7F\\\\\/]/u', $basename)) {
            self::reject($field, 'The uploaded file name contains unsupported characters.');
        }

        if ((bool) config('security.upload_reject_double_extensions', true)) {
            $nameWithoutLastExtension = pathinfo($basename, PATHINFO_FILENAME);
            if (str_contains($nameWithoutLastExtension, '.')) {
                self::reject($field, 'Files with multiple extensions are not permitted.');
            }
        }

        if (! (bool) config('security.upload_scan_enabled', false)) {
            return;
        }

        $scanner = (string) config('security.upload_scanner_command', '/usr/bin/clamscan');
        if (! function_exists('exec') || $scanner === '' || ! is_executable($scanner)) {
            self::reject($field, 'File scanning is required but the malware scanner is unavailable. Contact the system administrator.');
        }

        $path = $file->getRealPath();
        if (! is_string($path) || $path === '') {
            self::reject($field, 'The uploaded file could not be scanned.');
        }

        $command = escapeshellarg($scanner).' --no-summary '.escapeshellarg($path).' 2>&1';
        exec($command, $output, $exitCode);

        // ClamAV: 0 = clean, 1 = infected, 2 = error.
        if ($exitCode === 1) {
            self::reject($field, 'The uploaded file was rejected by malware scanning.');
        }

        if ($exitCode !== 0) {
            self::reject($field, 'The uploaded file could not be safely scanned. Contact the system administrator.');
        }
    }

    /**
     * Store an audit-safe display name. The physical storage name should
     * still be generated by Laravel/UUID/Str::random and never trust this value.
     */
    public static function safeOriginalName(UploadedFile $file): string
    {
        $name = basename(str_replace(["\0", "\r", "\n"], '', (string) $file->getClientOriginalName()));
        $name = preg_replace('/[^A-Za-z0-9 _().\-]/u', '_', $name) ?: 'uploaded_file';

        return mb_substr($name, 0, 255);
    }

    private static function reject(string $field, string $message): never
    {
        throw ValidationException::withMessages([$field => $message]);
    }
}
