@extends('layouts.app')
@section('title','Locum Pool')
@section('content')
@include('workforce.partials.style')
<div class="wf-page"><div class="wf-header"><div><h1 class="wf-title">Locum Pool, Booking & Reconciliation</h1><div class="wf-subtitle">Separate booking, performed session and reconciliation records preserve traceability.</div></div></div>
<div class="wf-grid"><div class="wf-card"><h3>Add/update locum</h3><form method="POST" action="{{route('workforce.locum-pool.profile.store')}}">@csrf<div class="wf-field"><label>Employee ID</label><input name="employee_id" type="number" required></div><div class="wf-field"><label>Status</label><select name="pool_status"><option>available</option><option>limited</option><option>unavailable</option></select></div><div class="wf-field"><label>Preferred session rate</label><input name="preferred_session_rate" type="number" step="0.01"></div><button class="wf-btn wf-btn-primary">Save</button></form></div><div class="wf-card"><h3>Book locum</h3><form method="POST" action="{{route('workforce.locum-pool.booking.store')}}">@csrf<div class="wf-field"><label>Employee ID</label><input name="employee_id" type="number" required></div><div class="wf-field"><label>Unit ID</label><input name="unit_id" type="number" required></div><div class="wf-field"><label>Date</label><input type="date" name="booking_date" required></div><div class="wf-field"><label>Start / End</label><input type="time" name="start_time" required><input type="time" name="end_time" required></div><div class="wf-field"><label>Reason</label><textarea name="request_reason" required></textarea></div><button class="wf-btn wf-btn-primary">Request booking</button></form></div></div>
<div class="wf-card" style="margin-top:14px"><h3>Pool</h3><table class="wf-table"><thead><tr><th>Locum</th><th>Status</th><th>Availability</th><th>Rate</th></tr></thead><tbody>@foreach($pool as $x)<tr><td>{{$x->employee?->display_name}}</td><td>{{$x->pool_status}}</td><td>{{$x->available_from}} - {{$x->available_to}}</td><td>{{$x->preferred_session_rate}}</td></tr>@endforeach</tbody></table></div>
<div class="wf-card" style="margin-top:14px"><h3>Bookings</h3><table class="wf-table"><thead><tr><th>Employee</th><th>Unit</th><th>Date</th><th>Status</th><th>Decision</th></tr></thead><tbody>@foreach($bookings as $b)<tr><td>{{$b->employee?->display_name}}</td><td>{{$b->unit?->name}}</td><td>{{$b->booking_date}} {{$b->start_time}}-{{$b->end_time}}</td><td>{{$b->status}}</td><td>@if($b->status==='requested')<form method="POST" action="{{route('workforce.locum-pool.booking.decide',$b)}}">@csrf<select name="action"><option value="approve">Approve</option><option value="reject">Reject</option></select><button class="wf-btn wf-btn-light">Decide</button></form>@endif</td></tr>@endforeach</tbody></table></div>
<div class="wf-card" style="margin-top:14px"><h3>Session reconciliation</h3><table class="wf-table"><thead><tr><th>Employee</th><th>Session</th><th>Calculated</th><th>Status</th><th>Reconcile</th></tr></thead><tbody>@forelse($sessions as $s)<tr><td>{{$s->employee?->display_name}}</td><td>{{$s->session_date}} {{$s->start_time}}-{{$s->end_time}}</td><td>{{$s->calculated_amount}}</td><td>{{$s->reconciliation_status}}</td><td><form method="POST" action="{{route('workforce.locum-pool.reconcile',$s)}}">@csrf<select name="status"><option value="verified">Verified</option><option value="exception">Exception</option></select><input name="external_payment_reference" placeholder="External payment ref"><input name="reconciliation_note" placeholder="Verification / exception note" required><button class="wf-btn wf-btn-primary">Record</button></form></td></tr>@empty<tr><td colspan="5">No unreconciled sessions.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection