@extends('layouts.app')
@section('title','Attendance Integrations')
@section('content')
@include('workforce.partials.style')
<div class="wf-page"><div class="wf-header"><div><h1 class="wf-title">Biometric & Multi-Punch Attendance</h1><div class="wf-subtitle">Private-sector integration layer. Carder stores punch metadata only; fingerprint/face templates stay in the vendor platform.</div></div></div>
<div class="wf-notice">Supported adapter patterns include Suprema BioStar 2 TA REST integration and configurable generic REST feeds. No biometric template is imported into Carder.</div>
@if(session('success'))<div class="wf-notice">{{session('success')}}</div>@endif @if($errors->any())<div class="wf-card" style="border-color:var(--md-error)">@foreach($errors->all() as $e)<div>{{$e}}</div>@endforeach</div>@endif
<div class="wf-card"><h3>Register integration</h3><form method="POST" action="{{route('workforce.attendance-integration.devices.store')}}">@csrf<div class="wf-form-grid"><div class="wf-field"><label>Name</label><input name="name" required></div><div class="wf-field"><label>Vendor</label><input name="vendor" placeholder="Suprema / Other" required></div><div class="wf-field"><label>Adapter</label><select name="adapter"><option value="biostar2_ta">Suprema BioStar 2 TA API</option><option value="generic_rest">Generic REST</option></select></div><div class="wf-field"><label>Base URL</label><input name="base_url" placeholder="https://attendance-server"></div><div class="wf-field"><label>Event/Punch Path</label><input name="event_path" placeholder="Configure from vendor API version"></div><div class="wf-field"><label>API Token (encrypted at rest)</label><input name="token" type="password"></div></div><button class="wf-btn wf-btn-primary" style="margin-top:12px">Save integration</button></form></div>
<div class="wf-card" style="margin-top:14px"><h3>Devices</h3><table class="wf-table"><thead><tr><th>Device</th><th>Adapter</th><th>Last sync</th><th>Map employee</th><th>Pull events</th></tr></thead><tbody>@forelse($devices as $d)<tr><td>{{$d->name}}<br><small>{{$d->vendor}}</small></td><td>{{$d->adapter}}</td><td>{{$d->last_sync_status}} {{$d->last_sync_at}}</td><td><form method="POST" action="{{route('workforce.attendance-integration.map',$d)}}">@csrf<input name="external_user_ref" placeholder="External user ID" required><input name="employee_id" type="number" placeholder="Employee ID" required><button class="wf-btn wf-btn-light">Map</button></form></td><td><form method="POST" action="{{route('workforce.attendance-integration.sync',$d)}}">@csrf<input name="from" type="date" value="{{now()->toDateString()}}"><input name="to" type="date" value="{{now()->toDateString()}}"><button class="wf-btn wf-btn-primary">Sync</button></form></td></tr>@empty<tr><td colspan="5">No integrations configured.</td></tr>@endforelse</tbody></table></div>
<div class="wf-card" style="margin-top:14px"><h3>Recent punch events</h3><table class="wf-table"><thead><tr><th>Time</th><th>Employee</th><th>External Ref</th><th>Type</th><th>Status</th></tr></thead><tbody>@foreach($punches as $x)<tr><td>{{$x->punched_at}}</td><td>{{$x->employee?->display_name ?? 'Unmapped'}}</td><td>{{$x->external_user_ref}}</td><td>{{$x->punch_type}}</td><td>{{$x->processing_status}}</td></tr>@endforeach</tbody></table></div></div>
@endsection