@extends('layouts.app')
@section('title', 'My Workforce Portal')
@section('content')
@include('workforce.partials.style')
<div class="wf-page"><div class="wf-header"><div><h1 class="wf-title">My Workforce Portal</h1><div class="wf-subtitle">Your roster, availability, attendance corrections, leave and finalized payroll information when that module is enabled.</div></div></div>
@if(session('success'))<div class="wf-notice">{{ session('success') }}</div>@endif
@if($errors->any())<div class="wf-notice" style="background:var(--md-error-container);color:var(--md-on-error-container)">{{ $errors->first() }}</div>@endif
@if(!$employeeId)<div class="wf-notice">Your user account is not linked to an employee record. Self-service actions are unavailable.</div>@else
<div class="wf-grid">
<div class="wf-card"><h3>Upcoming Roster</h3>@if(\App\Services\FeatureToggleService::enabled('roster'))<div style="margin-bottom:8px"><a class="wf-btn" href="{{ route('roster.employee.index') }}">Open My Roster Actions</a></div>@endif@forelse($roster as $r)<div style="padding:8px 0;border-bottom:1px solid var(--md-outline-variant)"><strong>{{ $r->duty_date?->format('Y-m-d') }}</strong> · {{ substr($r->start_time,0,5) }}–{{ substr($r->end_time,0,5) }} · {{ $r->dutyUnit?->name }}<form method="post" action="{{ route('workforce.self-service.swap.store',$r) }}" style="display:flex;gap:6px;margin-top:6px">@csrf<input type="hidden" name="swap_type" value="give_away"><input name="reason" placeholder="Reason for replacement/swap" required><button class="wf-btn">Request change</button></form></div>@empty<div class="wf-subtitle">No upcoming duties.</div>@endforelse</div>
<div class="wf-card"><h3>My Availability</h3><form method="post" action="{{ route('workforce.self-service.availability.store') }}" style="display:grid;gap:7px">@csrf<input type="hidden" name="employee_id" value="{{ $employeeId }}"><input type="date" name="available_date" required><select name="availability_type"><option value="available">Available</option><option value="preferred">Preferred</option><option value="unavailable">Unavailable</option></select><div style="display:flex;gap:6px"><input type="time" name="available_from"><input type="time" name="available_to"></div><select name="preferred_shift"><option value="">Any shift</option><option value="morning">Morning</option><option value="evening">Evening</option><option value="night">Night</option><option value="on_call">On-call</option></select><input name="note" placeholder="Optional note"><button class="wf-btn">Save availability</button></form>@foreach($availability as $a)<div style="margin-top:7px">{{ $a->available_date?->format('Y-m-d') }} · {{ ucfirst($a->availability_type) }}</div>@endforeach</div>
@if($leaveEnabled)<div class="wf-card"><h3>Recent Leave</h3>@forelse($leave as $r)<div>{{ $r->start_date?->format('Y-m-d') }} · {{ $r->leaveType?->name }} · {{ $r->status }}</div>@empty<div class="wf-subtitle">No leave requests.</div>@endforelse</div>@else<div class="wf-card"><h3>Leave</h3><div class="wf-subtitle">Digital Leave Management is disabled. For government deployments, the authorised paper-based leave process remains the official source unless the module is formally enabled by Super Admin governance.</div></div>@endif
<div class="wf-card"><h3>Attendance & Corrections</h3>@forelse($attendance as $r)<div style="padding:8px 0;border-bottom:1px solid var(--md-outline-variant)">{{ $r->work_date?->format('Y-m-d') }} · {{ $r->status }}<form method="post" action="{{ route('workforce.self-service.attendance-correction.store',$r) }}" style="display:grid;gap:5px;margin-top:6px">@csrf<input type="datetime-local" name="requested_clock_in_at"><input type="datetime-local" name="requested_clock_out_at"><input name="reason" placeholder="Correction reason" required><button class="wf-btn">Request correction</button></form></div>@empty<div class="wf-subtitle">No attendance records.</div>@endforelse</div>
@if(\App\Models\SystemSetting::getBool('feature_payroll',false))<div class="wf-card"><h3>Payslips</h3>@forelse($payslips as $r)<div>{{ $r->year }}-{{ str_pad($r->month,2,'0',STR_PAD_LEFT) }} · LKR {{ number_format($r->net_pay,2) }}</div>@empty<div class="wf-subtitle">No finalized payslips.</div>@endforelse</div>@endif
</div>@endif</div>
@endsection
