<?php
namespace App\Http\Controllers;
use App\Models\AttendanceDevice; use App\Models\AttendanceDeviceEmployeeMap; use App\Models\AttendancePunch; use App\Models\Employee; use App\Services\Attendance\AttendanceAdapterManager; use App\Services\Attendance\AttendancePunchService; use App\Services\WorkforceAuditService; use Carbon\Carbon; use Illuminate\Http\Request;
class AttendanceIntegrationController extends Controller {
 public function index(){ $devices=AttendanceDevice::latest()->get();$maps=AttendanceDeviceEmployeeMap::with(['employee','device'])->latest()->limit(100)->get();$punches=AttendancePunch::with('employee')->latest('punched_at')->limit(100)->get(); return view('workforce.attendance.integration',compact('devices','maps','punches')); }
 public function storeDevice(Request $r, WorkforceAuditService $audit){$d=$r->validate(['name'=>'required|string|max:120','vendor'=>'required|string|max:60','adapter'=>'required|in:biostar2_ta,generic_rest','base_url'=>'nullable|url|max:500','token'=>'nullable|string|max:2000','event_path'=>'nullable|string|max:250','user_field'=>'nullable|string|max:100','time_field'=>'nullable|string|max:100','type_field'=>'nullable|string|max:100','id_field'=>'nullable|string|max:100']);$m=AttendanceDevice::create(['name'=>$d['name'],'vendor'=>$d['vendor'],'adapter'=>$d['adapter'],'base_url'=>$d['base_url']??null,'encrypted_config'=>array_filter(['token'=>$d['token']??null,'punch_path'=>$d['event_path']??null,'event_path'=>$d['event_path']??null,'user_field'=>$d['user_field']??'user_id','time_field'=>$d['time_field']??'timestamp','type_field'=>$d['type_field']??'type','id_field'=>$d['id_field']??'id']),'created_by'=>auth()->id()]);$audit->model('created',$m,'Attendance integration device configured; biometric templates are not stored in Carder.');return back()->with('success','Attendance integration saved.'); }
 public function mapEmployee(Request $r, AttendanceDevice $device, WorkforceAuditService $audit){$d=$r->validate(['external_user_ref'=>'required|string|max:120','employee_id'=>'required|exists:employees,id']);$m=AttendanceDeviceEmployeeMap::updateOrCreate(['attendance_device_id'=>$device->id,'external_user_ref'=>trim($d['external_user_ref'])],['employee_id'=>$d['employee_id'],'is_active'=>true]);$audit->model('updated',$m,'Attendance device employee mapping saved');return back()->with('success','Employee mapping saved.'); }
 public function sync(Request $r, AttendanceDevice $device, AttendanceAdapterManager $manager, AttendancePunchService $punches, WorkforceAuditService $audit){$d=$r->validate(['from'=>'required|date','to'=>'required|date|after_or_equal:from']);$cfg=$device->encrypted_config?:[];try{$rows=$manager->for($device)->pull($device,Carbon::parse($d['from'])->startOfDay(),Carbon::parse($d['to'])->endOfDay());$accepted=0;foreach($rows as $row){$norm=['external_user_ref'=>data_get($row,$cfg['user_field']??'user_id'),'punched_at'=>data_get($row,$cfg['time_field']??'timestamp'),'punch_type'=>data_get($row,$cfg['type_field']??'type','unknown'),'source_reference'=>data_get($row,$cfg['id_field']??'id')];if(empty($norm['external_user_ref'])||empty($norm['punched_at']))continue;$punches->ingest($norm,$device->id);$accepted++;}$device->update(['last_sync_at'=>now(),'last_sync_status'=>'success','last_sync_message'=>$accepted.' events accepted']);$audit->model('updated',$device,'Attendance device sync completed');return back()->with('success',$accepted.' punch events imported.');}catch(\Throwable $e){$device->update(['last_sync_at'=>now(),'last_sync_status'=>'failed','last_sync_message'=>mb_substr($e->getMessage(),0,1000)]);return back()->withErrors(['sync'=>$e->getMessage()]);}}
 public function rebuild(Request $r, AttendancePunchService $service, WorkforceAuditService $audit){$d=$r->validate(['employee_id'=>'required|exists:employees,id','work_date'=>'required|date']);$rec=$service->rebuildDay((int)$d['employee_id'],$d['work_date']);$audit->model('updated',$rec,'Attendance rebuilt from multi-punch events');return back()->with('success','Daily attendance rebuilt from mapped punch events.');}
}
