<?php
namespace App\Http\Controllers;
use App\Models\ContractProbationReview; use App\Models\ContractRenewalRequest; use App\Models\EmployeeContract; use App\Services\WorkforceAuditService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class ContractLifecycleController extends Controller {
 public function index(){ $contracts=EmployeeContract::where('is_active',true)->orderByRaw('COALESCE(probation_end_date,end_date) asc')->limit(200)->get();$reviews=ContractProbationReview::with('contract')->latest()->limit(100)->get();$renewals=ContractRenewalRequest::with('contract')->latest()->limit(100)->get();return view('workforce.contracts.lifecycle',compact('contracts','reviews','renewals'));}
 public function createReview(Request $r,EmployeeContract $contract,WorkforceAuditService $audit){$d=$r->validate(['review_due_date'=>'required|date']);$m=ContractProbationReview::create(['employee_contract_id'=>$contract->id,'review_due_date'=>$d['review_due_date']]);$audit->model('created',$m,'Probation review scheduled');return back()->with('success','Probation review scheduled.');}
 public function decideReview(Request $r,ContractProbationReview $review,WorkforceAuditService $audit){$d=$r->validate(['recommendation'=>'required|in:confirm,extend,terminate','review_note'=>'required|string|max:2000','extended_to'=>'nullable|required_if:recommendation,extend|date']);$old=$review->toArray();$review->update(['status'=>'completed','recommendation'=>$d['recommendation'],'review_note'=>$d['review_note'],'reviewed_by'=>auth()->id(),'reviewed_at'=>now(),'extended_to'=>$d['extended_to']??null]);if($d['recommendation']==='confirm')$review->contract()->update(['status'=>'active']);elseif($d['recommendation']==='extend')$review->contract()->update(['probation_end_date'=>$d['extended_to']]);elseif($d['recommendation']==='terminate')$review->contract()->update(['status'=>'ended','is_active'=>false]);$audit->model('updated',$review,'Probation decision recorded',$old);return back()->with('success','Probation decision recorded.');}
 public function requestRenewal(Request $r,EmployeeContract $contract,WorkforceAuditService $audit){$d=$r->validate(['proposed_start_date'=>'required|date','proposed_end_date'=>'nullable|date|after_or_equal:proposed_start_date','reason'=>'required|string|max:1500','basic_salary'=>'nullable|numeric|min:0','hourly_rate'=>'nullable|numeric|min:0','session_rate'=>'nullable|numeric|min:0']);$terms=array_filter(['basic_salary'=>$d['basic_salary']??null,'hourly_rate'=>$d['hourly_rate']??null,'session_rate'=>$d['session_rate']??null],fn($v)=>$v!==null);$m=ContractRenewalRequest::create(['employee_contract_id'=>$contract->id,'proposed_start_date'=>$d['proposed_start_date'],'proposed_end_date'=>$d['proposed_end_date']??null,'proposed_terms'=>$terms,'reason'=>$d['reason'],'requested_by'=>auth()->id()]);$audit->model('created',$m,'Contract renewal requested');return back()->with('success','Contract renewal request created.');}
 public function decideRenewal(Request $r,ContractRenewalRequest $renewal,WorkforceAuditService $audit){$d=$r->validate(['action'=>'required|in:approve,reject','review_note'=>'required|string|max:1500']);$old=$renewal->toArray();DB::transaction(function()use($renewal,$d){$renewal->update(['status'=>$d['action']==='approve'?'approved':'rejected','reviewed_by'=>auth()->id(),'reviewed_at'=>now(),'review_note'=>$d['review_note']]);if($d['action']==='approve'){ $base=$renewal->contract;$attrs=$base->only(['employee_id','contract_type','basic_salary','pay_frequency','hourly_rate','session_rate','patient_rate','revenue_share_percent','cost_centre_id','terms_summary']);$attrs=array_merge($attrs,$renewal->proposed_terms?:[],['start_date'=>$renewal->proposed_start_date,'end_date'=>$renewal->proposed_end_date,'status'=>'active','is_active'=>true,'created_by'=>auth()->id()]);$new=EmployeeContract::create($attrs);$base->update(['status'=>'renewed','is_active'=>false]);$renewal->update(['new_contract_id'=>$new->id]);}});$audit->model('updated',$renewal,'Contract renewal decision recorded',$old);return back()->with('success','Renewal decision recorded.');}
}
