<?php
namespace App\Http\Controllers;
use App\Models\LeaveAccrualPolicy; use App\Models\LeaveType; use App\Services\LeaveAccrualService; use App\Services\WorkforceAuditService; use Illuminate\Http\Request;
class LeaveAutomationController extends Controller {
 public function index(LeaveAccrualService $svc){$policies=LeaveAccrualPolicy::with('leaveType')->latest()->get();$preview=$svc->preview((int)request('year',now()->year),request('month')? (int)request('month'):null)->take(100);return view('workforce.leave.automation',compact('policies','preview'));}
 public function storePolicy(Request $r,WorkforceAuditService $audit){$d=$r->validate(['leave_type_id'=>'required|exists:leave_types,id','contract_type'=>'nullable|string|max:40','accrual_frequency'=>'required|in:monthly,annual','accrual_amount'=>'required|numeric|min:0','annual_cap'=>'nullable|numeric|min:0','carry_forward_enabled'=>'nullable|boolean','carry_forward_cap'=>'nullable|numeric|min:0','effective_from'=>'required|date','effective_to'=>'nullable|date|after_or_equal:effective_from']);$d['support_only']=true;$d['carry_forward_enabled']=$r->boolean('carry_forward_enabled');$d['updated_by']=auth()->id();$m=LeaveAccrualPolicy::create($d);$audit->model('created',$m,'Support-only leave accrual policy created');return back()->with('success','Support-only leave policy saved.');}
 public function apply(Request $r,LeaveAccrualService $svc,WorkforceAuditService $audit){$d=$r->validate(['year'=>'required|integer|min:2000|max:2100','month'=>'nullable|integer|min:1|max:12','governance_note'=>'required|string|min:8|max:500']);$result=$svc->apply((int)$d['year'],$d['month']?(int)$d['month']:null,auth()->id(),$d['governance_note']);$audit->log('updated','LeaveAccrualRun',null,'Applied support-only leave accrual run: '.$d['governance_note'],null,$result);return back()->with('success',"Accrual support run applied to {$result['rows']} candidate rows ({$result['days']} days). It remains a support record, not an authority override.");}
 public function carry(Request $r,LeaveAccrualService $svc,WorkforceAuditService $audit){$d=$r->validate(['from_year'=>'required|integer','to_year'=>'required|integer|gt:from_year','governance_note'=>'required|string|min:8|max:500']);$result=$svc->carryForward((int)$d['from_year'],(int)$d['to_year'],auth()->id(),$d['governance_note']);$audit->log('updated','LeaveCarryForward',null,'Applied support-only carry forward: '.$d['governance_note'],null,$result);return back()->with('success',"Carry-forward support updated {$result['balances']} balances ({$result['days']} days).");}
}
