<?php
namespace App\Http\Controllers;
use App\Models\EmployeeContract; use App\Models\LocumBooking; use App\Models\LocumPoolProfile; use App\Models\LocumSession; use App\Services\WorkforceAuditService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class LocumPoolController extends Controller {
 public function index(){ $pool=LocumPoolProfile::with('employee')->where('is_active',true)->get();$bookings=LocumBooking::with(['employee','unit'])->latest('booking_date')->limit(100)->get();$sessions=LocumSession::with('employee')->whereIn('reconciliation_status',['unreconciled','exception'])->latest('session_date')->limit(100)->get();return view('workforce.locum.pool',compact('pool','bookings','sessions'));}
 public function saveProfile(Request $r,WorkforceAuditService $audit){$d=$r->validate(['employee_id'=>'required|exists:employees,id','pool_status'=>'required|in:available,limited,unavailable','preferred_hourly_rate'=>'nullable|numeric|min:0','preferred_session_rate'=>'nullable|numeric|min:0','available_from'=>'nullable|date','available_to'=>'nullable|date|after_or_equal:available_from','notes'=>'nullable|string|max:1500']);$d['updated_by']=auth()->id();$m=LocumPoolProfile::updateOrCreate(['employee_id'=>$d['employee_id']],$d);$audit->model('updated',$m,'Locum pool profile saved');return back()->with('success','Locum pool profile saved.');}
 public function book(Request $r,WorkforceAuditService $audit){$d=$r->validate(['employee_id'=>'required|exists:employees,id','unit_id'=>'required|exists:units,id','contract_id'=>'nullable|exists:employee_contracts,id','booking_date'=>'required|date','start_time'=>'required','end_time'=>'required','request_reason'=>'required|string|max:1500']);$d['requested_by']=auth()->id();$m=LocumBooking::create($d);$audit->model('created',$m,'Locum booking requested');return back()->with('success','Locum booking requested.');}
 public function decide(Request $r,LocumBooking $booking,WorkforceAuditService $audit){$d=$r->validate(['action'=>'required|in:approve,reject','note'=>'nullable|string|max:1000']);$old=$booking->toArray();if($d['action']==='approve'){
    $booking->update(['status'=>'approved','approved_by'=>auth()->id(),'approved_at'=>now()]);
    if (! $booking->locum_session_id) {
        $contract = $booking->contract_id ? EmployeeContract::find($booking->contract_id) : EmployeeContract::where('employee_id',$booking->employee_id)->where('is_active',true)->latest('start_date')->first();
        $session = LocumSession::create(['employee_id'=>$booking->employee_id,'contract_id'=>$contract?->id,'unit_id'=>$booking->unit_id,'session_date'=>$booking->booking_date,'start_time'=>$booking->start_time,'end_time'=>$booking->end_time,'calculation_method'=>'session','calculated_amount'=>(float)($contract?->session_rate??0),'status'=>'draft','recorded_by'=>auth()->id(),'booking_id'=>$booking->id,'reconciliation_status'=>'unreconciled']);
        $booking->update(['locum_session_id'=>$session->id]);
    }
}else{$booking->update(['status'=>'rejected']);}$audit->model('updated',$booking,'Locum booking decision',$old);return back()->with('success','Booking decision recorded.');}
 public function reconcile(Request $r,LocumSession $session,WorkforceAuditService $audit){$d=$r->validate(['status'=>'required|in:verified,exception','reconciliation_note'=>'required|string|max:1500','external_payment_reference'=>'nullable|string|max:120']);$old=$session->toArray();$session->update(['reconciliation_status'=>$d['status'],'reconciliation_note'=>$d['reconciliation_note'],'external_payment_reference'=>$d['external_payment_reference']??null,'verified_by'=>auth()->id(),'verified_at'=>now()]);$audit->model('updated',$session,'Locum session reconciled',$old);return back()->with('success','Session reconciliation recorded.');}
}
